# .github/workflows/prod.yml
name: Deploy Application Requirement Hub Frontend

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t eliasfernandescout/reqhubfront .
      - name: Push docker image
        run: docker push eliasfernandescout/reqhubfront

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Add user to docker group
        run: sudo usermod -aG docker $(whoami)
      - name: Pull image from docker hub
        run: docker pull eliasfernandescout/reqhubfront:latest
      - name: Remove docker container
        run: docker rm -f reqhubfront
      - name: Run docker container
        run: docker run -d -p 80:80 --name reqhubfront eliasfernandescout/reqhubfront